ARG NOMAD_VERSION

FROM ghcr.io/jumppad-labs/nomad:v${NOMAD_VERSION}

ARG NOMAD_VERSION
ARG CONSUL_VERSION
ARG TARGETARCH
ARG CNI_PLUGINS=1.5.1
ARG CONSUL_CNI_PLUGINS=1.6.1

# Install the Consul binary
RUN curl -L https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_${TARGETARCH}.zip -o /tmp/consul.zip && \
  cd /tmp && \
  unzip consul.zip -d /usr/bin && \
  chmod +x /usr/bin/consul && \
  rm /tmp/consul.zip

# Install the Consul CNI Plugins
RUN curl -L https://releases.hashicorp.com/consul-cni/${CONSUL_CNI_PLUGINS}/consul-cni_${CONSUL_CNI_PLUGINS}_linux_${TARGETARCH}.zip -o /tmp/consul_cni.zip && \
  unzip /tmp/consul_cni.zip -d /opt/cni/bin && \
  rm /tmp/consul_cni.zip