# Add QEMU
ARG NOMAD_VERSION

FROM ghcr.io/jumppad-labs/nomad:v${NOMAD_VERSION}

ARG NOMAD_VERSION
ARG TARGETARCH

RUN apt-get update && \
  apt-get install -y -o APT::Install-Suggests=0 -o APT::Install-Recommends=0 \
  qemu-system-x86 && \
  apt-get clean && rm -rf /var/lib/apt/lists/*