name: Kubernetes
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Kubernetes version
        id: collect
        run: |-
          # Get latest Kubernetes version
          KUBERNETES_VERSION=$(curl -s https://registry.hub.docker.com/v2/repositories/rancher/k3s/tags\?name\=k3s1  | jq -r '.results[]["name"] |  sub("(?<version>[0-9]+\\.[0-9]+\\.[0-9]+).*";.version)' | sort -V -r | head -n 1)
          CURRENT_VERSION=$(curl --silent --fail -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/jumppad-labs/packages/docker/kubernetes/versions | jq -r '.[]["name"]'| head -n 1)

          CURRENT_VERSION="v0.0.0"
          echo "version=$KUBERNETES_VERSION" >> "$GITHUB_OUTPUT"
          echo "current=$CURRENT_VERSION" >> "$GITHUB_OUTPUT"

          echo $KUBERNETES_VERSION
          echo $CURRENT_VERSION
      - name: Build image
        if: steps.collect.outputs.version != steps.collect.outputs.current
        run: |-
          echo "Building image"
