name: Kubernetes
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Kubernetes version
        run: |-
          # Get latest Kubernetes version
          KUBERNETES_VERSION=$(curl -s https://registry.hub.docker.com/v2/repositories/rancher/k3s/tags\?name\=k3s1  | jq -r '.results[]["name"] |  sub("(?<version>[0-9]+\\.[0-9]+\\.[0-9]+).*";.version)' | sort -V -r | head -n 1)
          CURRENT_VERSION=$(curl --silent --fail -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/jumppad-labs/packages/docker/kubernetes/versions | jq -r '.[]["name"]'| head -n 1)

          echo "::set-output name=version::$KUBERNETES_VERSION"
          echo "::set-output name=current::$CURRENT_VERSION"
      - name: Build image
        if: needs.build.outputs.version != needs.setup.outputs.current
        run: |-
          echo "Building image"
